services:
  postgres:
    image: postgres:16
    container_name: grog-postgres
    environment:
      POSTGRES_USER: grog
      POSTGRES_PASSWORD: grog
      POSTGRES_DB: grog
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - grog-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U grog -d grog"]
      interval: 5s
      timeout: 5s
      retries: 10

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: grog-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - grog-network

  auth-service:
    build: ./auth-service
    env_file: .env
    ports:
      - "8030:8030"
    command: sh -c "pip install --no-cache-dir bcrypt==4.0.1 && uvicorn app.main:app --host 0.0.0.0 --port 8030"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - grog-network

  simupay-service:
    build: ./simupay-integration-service
    env_file: .env
    ports:
      - "8020:8020"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8020
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - grog-network

  orchestrator-service:
    build: ./transaction-orchestrator-service
    env_file: .env
    ports:
      - "8010:8010"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8010
    depends_on:
      postgres:
        condition: service_healthy
      simupay-service:
        condition: service_started
    networks:
      - grog-network

  vending-service:
    build: ./vending-service
    env_file: .env
    ports:
      - "8040:8040"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8040
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - grog-network

  iot-service:
    build: ./iot-bridge-service
    env_file: .env
    ports:
      - "8050:8050"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8050
    depends_on:
      postgres:
        condition: service_healthy
      mosquitto:
        condition: service_started
    networks:
      - grog-network



  notification-service:
    build: ./notification-service
    ports:
      - "8070:8070"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8070
    networks:
      - grog-network

  payment-gateway:
    build: ../PaymentGateway-Service/api
    ports:
      - "8001:8001"
    volumes:
      - ../PaymentGateway-Service/api:/app
    environment:
      - INTERNAL_API_KEY=grog-simupay-secret
    networks:
      - grog-network

  payment-gateway-frontend:
    build: ../PaymentGateway-Service/frontend
    ports:
      - "5174:5174"
    networks:
      - grog-network


networks:
  grog-network:
    driver: bridge

volumes:
  pgdata:
